

# This file was *autogenerated* from the file parameter.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_55 = Integer(55); _sage_const_653 = Integer(653); _sage_const_1637 = Integer(1637); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_14 = Integer(14); _sage_const_30 = Integer(30); _sage_const_6 = Integer(6); _sage_const_100 = Integer(100)
def ceil_log_b(val, b):
    """
    計算 ceil(log_b(val))。
    使用純整數運算，避免大整數在計算浮點數 log 時遺失精準度。
    """
    if val <= _sage_const_1 :
        return _sage_const_0 
    res = _sage_const_0 
    curr = _sage_const_1 
    while curr < val:
        curr *= b
        res += _sage_const_1 
    return res

def find_valid_parameters(b=_sage_const_2 ): # 將 b 作為參數傳入，預設為 2
    print(f"開始搜尋參數 (使用底數 b = {b})")
    print(f"{'p':<6} | {'q':<20} | {'w':<6} | {'l':<10} | {'Check'}")
    print("-" * _sage_const_55 )

    # 1. 遍歷質數 p:[653, 761, 857, 953, 1013, 1277, 1601, 1609, 1613, 1621, 1637]
    for p in [_sage_const_653 , _sage_const_1637 ]:
        print(f"{p}")
        # 條件: p % 4 == 1
        if p % _sage_const_4  != _sage_const_1 :
            continue

        # 2. 遍歷 w
        # 條件: 2*p >= 3*w  =>  w <= 2*p/3
        max_w = floor((_sage_const_2  * p) / _sage_const_3 )
        
        # 為了演示，我們從一個合理的 w 大小開始
        start_w = max(_sage_const_1 , floor(p/_sage_const_5 )) 
        
        for w in range(start_w, max_w + _sage_const_1 ):
            
            # 3. 計算 q 的下界 (處理 l 的循環依賴)
            # 新公式: q >= 14w^2 + 30w^2*p + 6b*w*p*l + 6b*w*l + 1
            # l = log_b(q)
            
            # 初始猜測 l
            l = _sage_const_10 
            q_lower_bound = _sage_const_0 
            
            # 迭代修正 l，直到穩定
            for _ in range(_sage_const_10 ): # 稍微增加迭代次數以確保大底數也能收斂
                q_lower_bound = _sage_const_14 *(w**_sage_const_2 ) + _sage_const_30 *(w**_sage_const_2 )*p + _sage_const_6 *b*w*p*l + _sage_const_6 *b*w*l + _sage_const_1 
                new_l = ceil_log_b(q_lower_bound, b) 
                if new_l == l:
                    break
                l = new_l
            
            # 4. 尋找符合條件的質數 q
            # 從計算出的下界開始找下一個質數
            q = next_prime(q_lower_bound - _sage_const_1 )
            
            found_q = False
            # 設定一個搜尋上限，避免無限迴圈
            search_limit = _sage_const_100  
            count = _sage_const_0 
            
            while count < search_limit:
                # 條件: q % 6 == 1
                if q % _sage_const_6  == _sage_const_1 :
                    # 更新 l 以符合當前的 q (使用 log_b)
                    current_l = ceil_log_b(q, b)
                    
                    # 再次檢查 q 的大小限制，套用新公式
                    rhs = _sage_const_14 *(w**_sage_const_2 ) + _sage_const_30 *(w**_sage_const_2 )*p + _sage_const_6 *b*w*p*current_l + _sage_const_6 *b*w*current_l + _sage_const_1 
                    
                    if q >= rhs:
                        # 5. 檢查多項式不可約性
                        # 檢查 x^p - x - 1 在 GF(q) 上是否不可約
                        F = GF(q)
                        R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)
                        poly = x**p - x - _sage_const_1 
                        
                        if poly.is_irreducible():
                            assert p.is_prime()
                            assert q.is_prime()
                            assert w > _sage_const_0 
                            assert _sage_const_2 *p >= _sage_const_3 *w
                            # 替換為新的 assert 條件
                            assert q >= _sage_const_14 *w**_sage_const_2  + _sage_const_30 *w**_sage_const_2 *p + _sage_const_6 *b*w*p*current_l + _sage_const_6 *b*w*current_l + _sage_const_1 
                            assert q%_sage_const_6  == _sage_const_1 
                            assert p%_sage_const_4  == _sage_const_1 

                            print(f"{p:<6} | {q:<20} | {w:<6} | {current_l:<10} | Pass")
                            found_q = True
                            break 
                
                q = next_prime(q)
                count += _sage_const_1 
            
            if found_q:
                break

# 執行函式 (可以修改這裡的 b 值，例如 b=3, b=16 等等)
find_valid_parameters(b=_sage_const_2 **_sage_const_4 )

