

# This file was *autogenerated* from the file parameter.sage
from sage.all_cmdline import *   # import sage library

_sage_const_17 = Integer(17); _sage_const_1000 = Integer(1000); _sage_const_45 = Integer(45); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_14 = Integer(14); _sage_const_30 = Integer(30); _sage_const_12 = Integer(12); _sage_const_100 = Integer(100); _sage_const_6 = Integer(6); _sage_const_600 = Integer(600); _sage_const_15000 = Integer(15000)
def find_valid_parameters(start_p=_sage_const_17 , max_p=_sage_const_1000 ):
    print(f"開始搜尋參數 (p 範圍: {start_p} ~ {max_p})...")
    print(f"{'p':<6} | {'q':<20} | {'w':<6} | {'l':<10} | {'Check'}")
    print("-" * _sage_const_45 )

    # 1. 遍歷質數 p
    for p in primes(start_p, max_p):
        # 條件: p % 4 == 1
        if p % _sage_const_4  != _sage_const_1 :
            continue

        # 2. 遍歷 w
        # 條件: 2*p >= 3*w  =>  w <= 2*p/3
        max_w = floor((_sage_const_2  * p) / _sage_const_3 )
        
        # 為了演示，我們從一個合理的 w 大小開始 (例如 p/4)，避免 w 太小導致安全性不足
        # 也可以改為 range(1, max_w + 1)
        start_w = max(_sage_const_1 , floor(p/_sage_const_5 )) 
        
        for w in range(start_w, max_w + _sage_const_1 ):
            
            # 3. 計算 q 的下界 (處理 l 的循環依賴)
            # q >= 14w^2 + 30w^2*p + 12w*p*l + 12w*l + 1
            # l = log2(q)
            
            # 初始猜測 l (例如 10)
            l = _sage_const_10 
            q_lower_bound = _sage_const_0 
            
            # 迭代修正 l，直到穩定
            for _ in range(_sage_const_5 ):
                q_lower_bound = _sage_const_14 *(w**_sage_const_2 ) + _sage_const_30 *(w**_sage_const_2 )*p + _sage_const_12 *w*p*l + _sage_const_12 *w*l + _sage_const_1 
                new_l = Integer(q_lower_bound).nbits() # nbits ≈ ceil(log2(q))
                if new_l == l:
                    break
                l = new_l
            
            # 4. 尋找符合條件的質數 q
            # 從計算出的下界開始找下一個質數
            q = next_prime(q_lower_bound - _sage_const_1 )
            
            found_q = False
            # 設定一個搜尋上限，避免無限迴圈 (例如找接下來的 100 個質數)
            search_limit = _sage_const_100  
            count = _sage_const_0 
            
            while count < search_limit:
                # 條件: q % 6 == 1
                if q % _sage_const_6  == _sage_const_1 :
                    # 更新 l 以符合當前的 q
                    current_l = Integer(q).nbits()
                    
                    # 再次檢查 q 的大小限制 (因為 l 可能變大了)
                    rhs = _sage_const_14 *(w**_sage_const_2 ) + _sage_const_30 *(w**_sage_const_2 )*p + _sage_const_12 *w*p*current_l + _sage_const_12 *w*current_l + _sage_const_1 
                    
                    if q >= rhs:
                        # 5. 檢查多項式不可約性 (這是最耗時的一步)
                        # 檢查 x^p - x - 1 在 GF(q) 上是否不可約
                        F = GF(q)
                        R = PolynomialRing(F, names=('x',)); (x,) = R._first_ngens(1)
                        poly = x**p - x - _sage_const_1 
                        
                        if poly.is_irreducible():
                            assert p.is_prime()

                            assert q.is_prime()

                            assert w > _sage_const_0 

                            assert _sage_const_2 *p >= _sage_const_3 *w

                            assert q >= _sage_const_14 *w**_sage_const_2  + _sage_const_30 *w**_sage_const_2 *p + _sage_const_12 *w*p*current_l + _sage_const_12 *w*current_l + _sage_const_1 

                            assert q%_sage_const_6  == _sage_const_1 

                            assert p%_sage_const_4  == _sage_const_1 

                            print(f"{p:<6} | {q:<20} | {w:<6} | {current_l:<10} | Pass")
                            # 找到一組就回傳 (或是用 yield 繼續找)
                            # return (p, q, w) 
                            found_q = True
                            break 
                
                q = next_prime(q)
                count += _sage_const_1 
            
            # 如果只想找第一組符合的 p，可以在這裡 break
            if found_q:
                # 為了展示多樣性，這裡不 break，繼續找下一個 w
                pass

# 執行函式
find_valid_parameters(start_p=_sage_const_600 , max_p=_sage_const_15000 )

