

# This file was *autogenerated* from the file primehe_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_60 = Integer(60); _sage_const_2 = Integer(2); _sage_const_1000 = Integer(1000); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100)
import os
import time
import gc  # [新增] 載入 Python 的垃圾回收模組

print("=== 1. 載入 primehe.sage 核心 (PKE 模式 - 效能測試版) ===")
try:
    load('primehe.sage')
    print("-> 載入成功！")
except Exception as e:
    print(f"-> [錯誤] 無法載入 primehe.sage: {e}")
    exit()

# 隨機數生成器適配器
def system_random8():
    return int(os.urandom(_sage_const_1 )[_sage_const_0 ])

def run_pke_test_batch(sys_name, iterations):
    print(f"\n" + "="*_sage_const_60 )
    print(f"正在測試參數集: [{sys_name}] | 預計執行次數: {iterations}")
    print("="*_sage_const_60 )

    # 1. 設定參數
    try:
        setparameters(sys_name, system_random8)
        print(f"參數設定: p={p}, q={q}, w={w}")
    except Exception as e:
        print(f"[参数设置失败] {e}")
        return None

    add_correct_count = _sage_const_0 
    mult_correct_count = _sage_const_0 

    # 記錄時間的累加器
    time_keygen = _sage_const_0 
    total_time_encrypt = _sage_const_0 
    total_time_add = _sage_const_0 
    total_time_dec_add = _sage_const_0 
    total_time_mult = _sage_const_0 
    total_time_dec_mult = _sage_const_0 

    # 2. KeyGen (只執行一次)
    try:
        t_start = time.time()
        pk, sk, evk = ZKeyGen()
        time_keygen = time.time() - t_start
        print(f"  [KeyGen] 完成 (耗時: {time_keygen:.4f}s)")
    except Exception as e:
        print(f"[KeyGen 錯誤] {e}")
        return None

    print("  [開始迴圈測試] ", end="", flush=True)

    for i in range(iterations):
        # 印出簡單的進度點，避免畫面太亂
        if (i + _sage_const_1 ) % _sage_const_1  == _sage_const_0 :
            print(".", end="", flush=True)
            
        try:  
            # 3. 準備明文
            r1 = Inputs_random()
            r2 = Inputs_random()
            
            expected_add = R_fromR3(R3_fromR(r1 + r2))
            expected_mult = R_fromR3(R3_fromR(r1 * r2))

            # 4. 加密
            t_start_encrypt = time.time()
            c1 = ZEncrypt(r1, pk)
            c2 = ZEncrypt(r2, pk)
            total_time_encrypt += (time.time() - t_start_encrypt)
            
            # ==========================================
            # 測試 A: 同態加法
            # ==========================================
            try:
                t_add = time.time()
                c_add = homomorphic_add(c1, c2)
                total_time_add += (time.time() - t_add)

                t_add_dec = time.time()
                r_dec_add = ZDecrypt(c_add, sk)
                total_time_dec_add += (time.time() - t_add_dec)
                
                if r_dec_add == expected_add:
                    add_correct_count += _sage_const_1 
            except Exception as e:
                pass 

            # ==========================================
            # 測試 B: 同態乘法 
            # ==========================================
            try:
                t_mult = time.time()
                c_mult = homomorphic_mult(c1, c2, evk)
                total_time_mult += (time.time() - t_mult)
                
                t_mult_dec = time.time()
                r_dec_mult = ZDecrypt(c_mult, sk)
                total_time_dec_mult += (time.time() - t_mult_dec)
                
                if r_dec_mult == expected_mult:
                    mult_correct_count += _sage_const_1 
            except Exception as e:
                pass

        except Exception as e:
            pass

        # === [新增] 每回合結束後，強制釋放佔用記憶體的大變數 ===
        try:
            del r1, r2, expected_add, expected_mult, c1, c2
        except NameError: 
            import traceback
            print("[Key 釋放錯誤] 可能因為 KeyGen 失敗而未定義，詳細錯誤如下：")
            traceback.print_exc() 
        try:
            del c_add, r_dec_add
        except NameError: 
            import traceback
            print("[Key 釋放錯誤] 可能因為 KeyGen 失敗而未定義，詳細錯誤如下：")
            traceback.print_exc() 
        try:
            del c_mult, r_dec_mult
        except NameError: 
            import traceback
            print("[Key 釋放錯誤] 可能因為 KeyGen 失敗而未定義，詳細錯誤如下：")
            traceback.print_exc() 
        
        # 呼叫垃圾回收器，清理孤立的記憶體碎片
        gc.collect()
            
    print(" 完成!")

    # 計算平均時間
    avg_enc_ms = (total_time_encrypt / (_sage_const_2  * iterations)) * _sage_const_1000  
    avg_add_ms = (total_time_add / iterations) * _sage_const_1000 
    avg_dec_add_ms = (total_time_dec_add / iterations) * _sage_const_1000 
    avg_mult_ms = (total_time_mult / iterations) * _sage_const_1000 
    avg_dec_mult_ms = (total_time_dec_mult / iterations) * _sage_const_1000 

    # === [新增] 準備離開函式前，釋放該參數集的 Keys ===
    try:
        del pk, sk, evk
    except NameError: 
        import traceback
        print("[Key 釋放錯誤] 可能因為 KeyGen 失敗而未定義，詳細錯誤如下：")
        traceback.print_exc()   
    gc.collect()

    return {
        "add_score": add_correct_count,
        "mult_score": mult_correct_count,
        "t_keygen_s": time_keygen,
        "t_enc_ms": avg_enc_ms,
        "t_add_ms": avg_add_ms,
        "t_dec_add_ms": avg_dec_add_ms,
        "t_mult_ms": avg_mult_ms,
        "t_dec_mult_ms": avg_dec_mult_ms
    }

# --- 主程式 ---

print("\n=== 2. 開始執行同態運算效能評估 ===")

systems_to_test = ['sntrupHo1637'] 
#systems_to_test = ['sntrupHo653', 'sntrupHo761', 'sntrupHo857', 'sntrupHo953', 'sntrupHo1013', 'sntrupHo1277', 'sntrupHo1609', 'sntrupHo1637']

results = {}
iterations = _sage_const_10   # 設定為跑 10 次取平均 (測試用)

for sys_name in systems_to_test:
    res = run_pke_test_batch(sys_name, iterations)
    if res:
        results[sys_name] = res

# --- 輸出最終數據表 ---
print("\n" + "="*_sage_const_100 )
print(f" {'Performance Analysis (Average over iterations)':^98} ")
print("="*_sage_const_100 )
print(f"{'Parameter Set':<15} | {'KeyGen (s)':<12} | {'Encrypt (ms)':<12} | {'Add (ms)':<10} | {'Mult (ms)':<12} | {'Decrypt (ms)':<12}")
print("-" * _sage_const_100 )

for name, data in results.items():
    t_keygen = float(data['t_keygen_s'])
    t_enc    = float(data['t_enc_ms'])
    t_add    = float(data['t_add_ms'])
    t_mult   = float(data['t_mult_ms'])
    t_dec    = float(data['t_dec_mult_ms'])
    
    print(f"{name:<15} | {t_keygen:>12.4f} | {t_enc:>12.2f} | {t_add:>10.4f} | {t_mult:>12.2f} | {t_dec:>12.2f}")

print("-" * _sage_const_100 )
print("Success Rates:")
for name, data in results.items():
    add_rate = (float(data['add_score']) / iterations) * _sage_const_100 
    mult_rate = (float(data['mult_score']) / iterations) * _sage_const_100 
    print(f" - {name}: Add {add_rate:.1f}%, Mult {mult_rate:.1f}%")
print("="*_sage_const_100 )

