

# This file was *autogenerated* from the file primehe.sage
from sage.all_cmdline import *   # import sage library

_sage_const_761 = Integer(761); _sage_const_4591 = Integer(4591); _sage_const_143 = Integer(143); _sage_const_653 = Integer(653); _sage_const_4621 = Integer(4621); _sage_const_144 = Integer(144); _sage_const_857 = Integer(857); _sage_const_5167 = Integer(5167); _sage_const_161 = Integer(161); _sage_const_953 = Integer(953); _sage_const_6343 = Integer(6343); _sage_const_198 = Integer(198); _sage_const_1013 = Integer(1013); _sage_const_7177 = Integer(7177); _sage_const_224 = Integer(224); _sage_const_1277 = Integer(1277); _sage_const_7879 = Integer(7879); _sage_const_246 = Integer(246); _sage_const_67280421310721 = Integer(67280421310721); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_32 = Integer(32); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_256 = Integer(256); _sage_const_65536 = Integer(65536); _sage_const_16777216 = Integer(16777216); _sage_const_31 = Integer(31); _sage_const_0x3fffffff = Integer(0x3fffffff); _sage_const_30 = Integer(30); _sage_const_16 = Integer(16); _sage_const_64 = Integer(64); _sage_const_16384 = Integer(16384); _sage_const_255 = Integer(255); _sage_const_5 = Integer(5); _sage_const_6144 = Integer(6144); _sage_const_8 = Integer(8); _sage_const_1218 = Integer(1218); _sage_const_1536 = Integer(1536); _sage_const_1015 = Integer(1015)
import sys

# TODO
# 設計足夠大的q以支援Homomorphic Multiplication

# Python 3 bytes 處理
def to_bytes(n):
    return bytes([n])

# 參數集定義
sntrup = { # round1, p, q, w, lpr
  'sntrup4591761': (True, _sage_const_761 , _sage_const_4591 , _sage_const_143 , False),
  'sntrup761':    (False, _sage_const_761 , _sage_const_4591 , _sage_const_143 , False),
  'sntrup653':    (False, _sage_const_653 , _sage_const_4621 , _sage_const_144 , False),
  'sntrup857':    (False, _sage_const_857 , _sage_const_5167 , _sage_const_161 , False),
  'sntrup953':    (False, _sage_const_953 , _sage_const_6343 , _sage_const_198 , False),
  'sntrup1013':   (False, _sage_const_1013 , _sage_const_7177 , _sage_const_224 , False),
  'sntrup1277':   (False, _sage_const_1277 , _sage_const_7879 , _sage_const_246 , False),
  'sntrupHo':     (False, _sage_const_653 , _sage_const_67280421310721 , _sage_const_10 , False),
}

def setparameters(system, random8):
  global round1
  global p
  global q
  global w
  
  global PublicKeys_bytes
  global SecretKeys_bytes
  global Ciphertexts_bytes
  global Inputs_bytes
  global Rq_encode
  global Inputs_random
  global ZKeyGen
  global ZEncrypt
  global ZDecrypt
  global homomorphic_add
  global mult_count

  mult_count = _sage_const_1 
  if system in sntrup:
    round1, p, q, w, lpr_flag = sntrup[system]
    
    assert lpr_flag == False
  else:
    raise Exception('%s is not one of the selected parameter sets' % system)

  assert p.is_prime()
  assert q.is_prime()
  assert w > _sage_const_0 
  assert _sage_const_2 *p >= _sage_const_3 *w
  assert q >= _sage_const_32 *w+_sage_const_1 
  assert q%_sage_const_6  == _sage_const_1 
  assert p%_sage_const_4  == _sage_const_1 

  if round1:
    assert p == _sage_const_761 
    assert q == _sage_const_4591 

  # ----- 1. 數學結構定義 (Arithmetic) -----

  # Mod 3
  F3 = GF(_sage_const_3 )
  def ZZ_fromF3(c):
    assert c in F3
    return ZZ(c+_sage_const_1 )-_sage_const_1 

  # Mod q
  Fq = GF(q)
  q12 = ZZ((q-_sage_const_1 )/_sage_const_2 )
  def ZZ_fromFq(c):
    assert c in Fq
    return ZZ(c+q12)-q12

  # 整數多項式環 R
  global R
  Zx = ZZ['x']; (x,) = Zx._first_ngens(1)
  R = Zx.quotient(x**p-x-_sage_const_1 , names=('xp',)); (xp,) = R._first_ngens(1)

  def Weightw_is(r):
    assert r in R
    return w == len([i for i in range(p) if r[i] != _sage_const_0 ])

  def Small_is(r):
    assert r in R
    return all(abs(r[i]) <= _sage_const_1  for i in range(p))

  def Short_is(r):
    return Small_is(r) and Weightw_is(r)

  # Mod 3 多項式環 R3
  F3x = F3['x3']; (x3,) = F3x._first_ngens(1)
  R3 = F3x.quotient(x**p-x-_sage_const_1 , names=('x3p',)); (x3p,) = R3._first_ngens(1)

  global R_fromR3
  def R_fromR3(r):
    assert r in R3
    return R([ZZ_fromF3(r[i]) for i in range(p)])

  global R3_fromR
  def R3_fromR(r):
    assert r in R
    return R3([r[i] for i in range(p)])

  # Mod q 多項式環 Rq
  Fqx = Fq['xq']; (xq,) = Fqx._first_ngens(1)
  assert (xq**p-xq-_sage_const_1 ).is_irreducible()

  global Rq
  Rq = Fqx.quotient(x**p-x-_sage_const_1 , names=('xqp',)); (xqp,) = Rq._first_ngens(1)

  global R_fromRq
  def R_fromRq(r):
    assert r in Rq
    return R([ZZ_fromFq(r[i]) for i in range(p)])

  global Rq_fromR
  def Rq_fromR(r):
    assert r in R
    return Rq([r[i] for i in range(p)])

  # ----- 2. 輔助運算 (Rounding & Sorting) -----

  def Rounded_is(r):
    assert r in R
    return (all(r[i]%_sage_const_3  == _sage_const_0  for i in range(p))
      and all(r[i] >= -q12 for i in range(p))
      and all(r[i] <= q12 for i in range(p)))

  def Round(a):
    assert a in Rq
    c = R_fromRq(a)
    r = [_sage_const_3 *round(c[i]/_sage_const_3 ) for i in range(p)]
    assert all(abs(r[i]-c[i]) <= _sage_const_1  for i in range(p))
    r = R(r)
    assert Rounded_is(r)
    return r

  global Short_fromlist
  def Short_fromlist(L): # L is list of p uint32
    L = [L[i]&-_sage_const_2  for i in range(w)] + [(L[i]&-_sage_const_3 )|_sage_const_1  for i in range(w,p)]
    assert all(L[i]%_sage_const_2  == _sage_const_0  for i in range(w))
    assert all(L[i]%_sage_const_4  == _sage_const_1  for i in range(w,p))
    L.sort()
    L = [(L[i]%_sage_const_4 )-_sage_const_1  for i in range(p)]
    assert all(abs(L[i]) <= _sage_const_1  for i in range(p))
    assert sum(abs(L[i]) for i in range(p)) == w
    r = R(L)
    assert Short_is(r)
    return r

  # ----- 3. 隨機數生成 (Randomness) -----

  def urandom32():
    c0 = random8()
    c1 = random8()
    c2 = random8()
    c3 = random8()
    return c0 + _sage_const_256 *c1 + _sage_const_65536 *c2 + _sage_const_16777216 *c3

  global Short_random
  def Short_random(): 
    if round1:
      L = [urandom32() for i in range(p)]
      L = [L[i].__xor__(_sage_const_1 <<_sage_const_31 ) for i in range(p)]
      return Short_fromlist(L)

    L = [urandom32() for i in range(p)]
    return Short_fromlist(L)

  def randomrange3():
    return ((urandom32() & _sage_const_0x3fffffff ) * _sage_const_3 ) >> _sage_const_30 

  def Small_random():
    r = R([randomrange3()-_sage_const_1  for i in range(p)])
    assert Small_is(r)
    return r

  # ----- 4. 核心邏輯 (Core PKE Logic) -----

  
  global TensorProduct_poly
  global KeyGen
  global Encrypt
  global Decrypt


  def TensorProduct_poly(vec_a, vec_b):
    """
    計算兩個多項式向量的張量積 
    
    數學定義:
    若 vec_a = [a0, a1], vec_b = [b0, b1]
    結果 = [a0*b0, a0*b1, a1*b0, a1*b1]
    
    輸入:
        vec_a: List of polynomials in R (長度 n)
        vec_b: List of polynomials in R (長度 m)
    輸出:
        List of polynomials in R (長度 n * m)
    """
    result_vector = []
    
    # 雙層迴圈遍歷每一對元素
    for p1 in vec_a:
        for p2 in vec_b:
            # 在 R 環中進行多項式乘法
            prod = p1 * p2
            result_vector.append(prod)
            
    return result_vector

  def KeyGen():
    while True:
      g = Small_random()
      f = Short_random()
      h = Rq_fromR(g)/Rq_fromR(_sage_const_3 *f)
      if Rq_fromR(g).is_unit(): break
    """
    產生 Evaluation Key
    Formula: evk = [ (3f)^-1 P((D(3f) ⊗ D(3f)) ) + h'*s + e ]_q
    """
    # 1. 準備變數
    three_f = _sage_const_3 *f
    
    # 3. 計算 BitDecompose(3f)
    vec_D = BitDecompose_poly(three_f)
    
    # 計算 Tensor Product D ⊗ D
    DD = TensorProduct_poly(vec_D, vec_D)
    
    # 4. 構建 EVK
    # 這是一個 l x l x l 的三維結構，我們將其展平為列表
    # 公式: evk = [ (3f)^-1 *P(  (D(3f) ⊗ D(3f)) ) + h'*s + e ]_q
    evk_list = []
    
    hprime = R_fromR3(R3_fromR(R_fromRq(h)))
    for tensor in DD:
        
        power_evk_poly = PowerOf2_poly(tensor)
        
        for p in power_evk_poly:
            s = Small_random()
            error = Small_random()
            p = Rq_fromR(p)/Rq_fromR(three_f)+Rq_fromR(hprime * s + error)
            p = R_fromRq(p)
            evk_list.append(p)

    return h,(f,_sage_const_1 /R3_fromR(g)), evk_list
    # return h,(f,1/R3_fromR(g))

  def Encrypt(m,h):
    #assert Short_is(r)
    assert h in Rq
    return Round(h*Rq_fromR(m))

  def Decrypt(c,k):
    global mult_count
    f,v = k
    #assert Rounded_is(c)
    assert Short_is(f)
    assert v in R3
    # print(f"list(3*Rq_fromR(f)*Rq_fromR(c)) = {list(R_fromRq(3*Rq_fromR(f)*Rq_fromR(c)))}")
    r = R3_fromR(R_fromRq(_sage_const_3 *Rq_fromR(f)*Rq_fromR(c)))
    m = R_fromR3(r*v)
    mult_count -= _sage_const_1 
    while mult_count>_sage_const_0 :
        m = R_fromR3(r*v)
        mult_count -= _sage_const_1 
    return m
    #if Weightw_is(r): return r
    #return R([1]*w+[0]*(p-w))

  # ----- 5. 編碼與解碼 (Encoding/Decoding) -----

  global tostring
  def tostring(s):
    return bytes(s)

  def fromstring(s):
    return list(s)

  # Small Polynomial Encoding
  Small_bytes = ceil(p/_sage_const_4 )

  def Small_encode(r):
    assert Small_is(r)
    R = [r[i]+_sage_const_1  for i in range(p)]
    while len(R) < _sage_const_4 *Small_bytes: R += [_sage_const_0 ]
    assert all(R[i] >= _sage_const_0  for i in range(_sage_const_4 *Small_bytes))
    assert all(R[i] <= _sage_const_2  for i in range(_sage_const_4 *Small_bytes))
    assert len(R) >= p
    assert len(R)%_sage_const_4  == _sage_const_0 
    S = [R[i]+_sage_const_4 *R[i+_sage_const_1 ]+_sage_const_16 *R[i+_sage_const_2 ]+_sage_const_64 *R[i+_sage_const_3 ] for i in range(_sage_const_0 ,len(R),_sage_const_4 )]
    return tostring(S)

  def Small_decode(s):
    S = fromstring(s)
    r = [(S[i//_sage_const_4 ]//_sage_const_4 **(i%_sage_const_4 ))%_sage_const_4  for i in range(p)]
    assert all(r[i] >= _sage_const_0  for i in range(p))
    assert all(r[i] <= _sage_const_2  for i in range(p))
    r = [r[i]-_sage_const_1  for i in range(p)]
    return R(r)

  # General Infrastructure for Encoding
  if round1:
    import itertools
    def concat(lists): return list(itertools.chain.from_iterable(lists))
    def int2str(u,bytes_len): return bytes([(u//_sage_const_256 **i)%_sage_const_256  for i in range(bytes_len)])
    def str2int(s): return sum(s[i]*_sage_const_256 **i for i in range(len(s)))
    def seq2str(u,radix,batch,bytes_len): 
      return b''.join(int2str(sum(u[i+t]*radix**t for t in range(batch)),bytes_len)
                     for i in range(_sage_const_0 ,len(u),batch))
    def str2seq(s,radix,batch,bytes_len):
      u = [str2int(s[i:i+bytes_len]) for i in range(_sage_const_0 ,len(s),bytes_len)]
      return concat([(u[i]//radix**j)%radix for j in range(batch)] for i in range(len(u)))
  else:
    limit = _sage_const_16384 
    def Encode(R,M):
      if len(M) == _sage_const_0 : return []
      S = []
      if len(M) == _sage_const_1 :
        r,m = R[_sage_const_0 ],M[_sage_const_0 ]
        while m > _sage_const_1 :
          S += [r%_sage_const_256 ]
          r,m = r//_sage_const_256 ,(m+_sage_const_255 )//_sage_const_256 
        return S
      R2,M2 = [],[]
      for i in range(_sage_const_0 ,len(M)-_sage_const_1 ,_sage_const_2 ):
        m,r = M[i]*M[i+_sage_const_1 ],R[i]+M[i]*R[i+_sage_const_1 ]
        while m >= limit:
          S += [r%_sage_const_256 ]
          r,m = r//_sage_const_256 ,(m+_sage_const_255 )//_sage_const_256 
        R2 += [r]
        M2 += [m]
      if len(M)&_sage_const_1 :
        R2 += [R[-_sage_const_1 ]]
        M2 += [M[-_sage_const_1 ]]
      return S+Encode(R2,M2)
    def Decode(S,M):
      if len(M) == _sage_const_0 : return []
      if len(M) == _sage_const_1 : return [sum(S[i]*_sage_const_256 **i for i in range(len(S)))%M[_sage_const_0 ]]
      k = _sage_const_0 
      bottom,M2 = [],[]
      for i in range(_sage_const_0 ,len(M)-_sage_const_1 ,_sage_const_2 ):
        m,r,t = M[i]*M[i+_sage_const_1 ],_sage_const_0 ,_sage_const_1 
        while m >= limit:
          r,t,k,m = r+S[k]*t,t*_sage_const_256 ,k+_sage_const_1 ,(m+_sage_const_255 )//_sage_const_256 
        bottom += [(r,t)]
        M2 += [m]
      if len(M)&_sage_const_1 :
        M2 += [M[-_sage_const_1 ]]
      R2 = Decode(S[k:],M2)
      R = []
      for i in range(_sage_const_0 ,len(M)-_sage_const_1 ,_sage_const_2 ):
        r,t = bottom[i//_sage_const_2 ]
        r += t*R2[i//_sage_const_2 ]
        R += [r%M[i]]
        R += [(r//M[i])%M[i+_sage_const_1 ]]
      if len(M)&_sage_const_1 :
        R += [R2[-_sage_const_1 ]]
      return R

  # Rq Encoding
  if round1:
    def Rq_encode(h):
      h = [q12 + ZZ_fromFq(h[i]) for i in range(p)] + [_sage_const_0 ]*(-p % _sage_const_5 )
      return seq2str(h,_sage_const_6144 ,_sage_const_5 ,_sage_const_8 )[:_sage_const_1218 ]
    def Rq_decode(hstr):
      h = str2seq(hstr,_sage_const_6144 ,_sage_const_5 ,_sage_const_8 )
      if max(h) >= q: raise Exception('pk out of range')
      return Rq([h[i]-q12 for i in range(p)])
  else:
    def Rq_encode(r):
      assert r in Rq
      R = [ZZ_fromFq(r[i])+q12 for i in range(p)]
      M = [q]*p
      assert all(_sage_const_0  <= R[i] for i in range(p))
      assert all(R[i] < M[i] for i in range(p))
      return tostring(Encode(R,M))
    def Rq_decode(s):
      assert len(s) == Rq_bytes
      M = [q]*p
      R = Decode(fromstring(s),M)
      assert all(_sage_const_0  <= R[i] for i in range(p))
      assert all(R[i] < M[i] for i in range(p))
      r = [R[i]-q12 for i in range(p)]
      return Rq(r)

  global Rq_bytes
  Rq_bytes = len(Rq_encode(Rq(_sage_const_0 )))

  # Rounded Encoding
  if round1:
    q61 = ZZ((q-_sage_const_1 )/_sage_const_6 )
    def Rounded_encode(c):
      c = [q61 + ZZ(c[i]/_sage_const_3 ) for i in range(p)] + [_sage_const_0 ]*(-p % _sage_const_6 )
      return seq2str(c,_sage_const_1536 ,_sage_const_3 ,_sage_const_4 )[:_sage_const_1015 ]
    def Rounded_decode(cstr):
      c = str2seq(cstr,_sage_const_1536 ,_sage_const_3 ,_sage_const_4 )
      c = [ci%(q61*_sage_const_2 +_sage_const_1 ) for ci in c]
      return _sage_const_3 *R([c[i]-q61 for i in range(p)])
  else:
    def Rounded_encode(r):
      assert Rounded_is(r)
      R = [ZZ((ZZ_fromFq(r[i])+q12)/_sage_const_3 ) for i in range(p)]
      M = [ZZ((q-_sage_const_1 )/_sage_const_3 +_sage_const_1 )]*p
      assert all(_sage_const_0  <= R[i] for i in range(p))
      assert all(R[i] < M[i] for i in range(p))
      return tostring(Encode(R,M))
    def Rounded_decode(s):
      assert len(s) == Rounded_bytes
      M = [ZZ((q-_sage_const_1 )/_sage_const_3 +_sage_const_1 )]*p
      r = Decode(fromstring(s),M)
      assert all(_sage_const_0  <= r[i] for i in range(p))
      assert all(r[i] < M[i] for i in range(p))
      r = [_sage_const_3 *r[i]-q12 for i in range(p)]
      return R(r)

  global Rounded_bytes
  Rounded_bytes = len(Rounded_encode(R(_sage_const_0 )))

  # ----- 6. PKE Interface (Z-Functions) -----

  Inputs_random = Short_random
  Inputs_bytes = Small_bytes
  Ciphertexts_bytes = Rounded_bytes
  SecretKeys_bytes = _sage_const_2 *Small_bytes
  PublicKeys_bytes = Rq_bytes

  # 生成加密用的公鑰 (pk) 與私鑰 (sk)
  # 回傳: (bytes, bytes)
  def ZKeyGen():
    h, (f, v), evk = KeyGen()
    return Rq_encode(h), Small_encode(f) + Small_encode(R_fromR3(v)), evk
    # h, (f, v), evk = KeyGen()
    # return Rq_encode(h), Small_encode(f) + Small_encode(R_fromR3(v)), evk

  # 使用公鑰 pk 對多項式 m 進行加密
  # 輸入: m (Polynomial), pk (bytes)
  # 回傳: c (bytes)
  def ZEncrypt(m, pk):
    assert len(pk) == PublicKeys_bytes
    h = Rq_decode(pk)
    return Encrypt(m, h)
    #return Rounded_encode(Encrypt(m, h))

  # 使用私鑰 sk 對密文 c 進行解密
  # 輸入: c (bytes), sk (bytes)
  # 回傳: r (Polynomial)
  def ZDecrypt(c, sk):
    assert len(sk) == SecretKeys_bytes
    #assert len(c) == Ciphertexts_bytes
    f = Small_decode(sk[:Small_bytes])
    v = R3_fromR(Small_decode(sk[Small_bytes:]))
    #c = Rounded_decode(c)
    return Decrypt(c, (f, v))

  def homomorphic_add(c_1, c_2):
    c_sum = R_fromRq(Rq_fromR(c_1) + Rq_fromR(c_2))
    return c_sum
  
  global get_log_q
  global BitDecompose_poly
  global PowerOf2_poly
  global Gadget_Product
  global Vector_DotProduct

  def get_log_q():
    """計算需要的位元數 l = ceil(log2(q))"""
    return Integer(q).nbits()
  
  def BitDecompose_poly(A):
    """
    輸入: A (必須是 R 中的多項式, Integer Polynomial)
    輸出: [p0, p1, ..., pl-1] (每個 pi 都是 R 中的多項式)
    """
    # 1. 取得位元長度 l = ceil(log2(q))
    # 這裡使用 Integer(q) 確保可以呼叫 nbits 方法
    l = Integer(q).nbits()

    # 2. 驗證輸入型別 (根據您的要求)
    # 如果 A 不是 R 的元素，這裡會報錯，或者您可以選擇在此處強制轉型 A = R(A)
    if A.parent() != R:
        # 為了容錯，如果傳進來的是 Rq，我們嘗試轉回 R
        # 但如果傳入的是 list 或 int，這行會報錯
        try:
            A = R(A)
        except TypeError:
            raise TypeError(f"BitDecompose 輸入必須是 R 中的多項式，目前是: {A.parent()}")

    # 3. 係數正規化 (Normalization)
    # 這是最關鍵的一步！
    # R 中的多項式係數可能是負的 (例如 -1, 0, 1)。
    # 在進行位元分解前，我們必須將其映射到 [0, q-1] 的正整數區間。
    # Python 的 % 運算子對負數處理得很好: -1 % 4591 = 4590
    raw_coeffs = list(A)
    coeffs = [int(c) % q for c in raw_coeffs]
    
    # 補齊長度到 p (Sage 有時會省略高次項的 0)
    if len(coeffs) < p:
        coeffs += [_sage_const_0 ] * (p - len(coeffs))
    
    # 4. 進行位元分解
    # 我們直接建立 l 個係數列表，最後再轉成多項式
    poly_list = []
    
    for i in range(l):
        # 對於第 i 層，取出所有係數的第 i 個 bit
        # bit_row 是一個長度為 p 的整數列表 (內容只有 0 或 1)
        bit_row = [(c >> i) & _sage_const_1  for c in coeffs]
        
        # 5. [關鍵] 將列表轉為 R (整數環) 的多項式
        # 這確保了後續與 evk (如果 evk 也是 R) 運算時不會有型別衝突
        poly_in_R = R(bit_row)
        poly_list.append(poly_in_R)
        
    return poly_list

  def PowerOf2_poly(B):
    """
    輸入: 多項式 B (在 R 中)
    輸出: 多項式向量 [B, 2B, 4B, ..., 2^(l-1)B]
    """
    assert B in R

    l = get_log_q()
    
    # 生成 2 的冪次列表
    result_vector = []
    for i in range(l):
        scale = _sage_const_2 **i
        result_vector.append(R_fromRq(Rq_fromR(B * scale)))
        
    return result_vector

  def Vector_DotProduct(A, B):
    """
    計算兩個多項式向量的內積
    A, B: List of polynomials in R
    回傳: Single polynomial in R
    """
    if len(A) != len(B):
        raise ValueError("向量長度不一致")
    return sum(a * b for a, b in zip(A, B))
  
  def KeySwitch(c_mult_tilde_D, evk):
    return R_fromRq(Vector_DotProduct(c_mult_tilde_D, evk))
  
  global homomorphic_mult
  def homomorphic_mult(c_1,c_2,evk):

    # 1. 計算 P(c1) 和 P(c2)
    # vec1 和 vec2 都是長度為 l 的向量
    vec1 = PowerOf2_poly(c_1)
    vec2 = PowerOf2_poly(c_2)
    
    c_tilde = []
    
    # 2. 計算張量積 (Tensor Product)
    # 數學上是對每一對元素做乘法: v1[i] * v2[j]
    # 我們將 l x l 的矩陣展平為長度 l^2 的向量
    c_tilde = TensorProduct_poly(vec1, vec2)
    
    c_mult_tilde_B = []
    # 3. 使用 Evaluation Key 進行 Key Switching
    for c in c_tilde:
        for cB in BitDecompose_poly(c):
            c_mult_tilde_B.append(cB)
    

    c_mult = KeySwitch(c_mult_tilde_B, evk)
    return c_mult

